name: Build
permissions:
  contents: read
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from repo
        uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: 'yarn'
      - run: yarn
      - run: yarn lint
      - run: yarn build
      - name: Generate Supabase types
        run: |
          yarn supabase:start
          yarn supabase:types
      - name: Verify no uncommitted changes
        run: |
          git diff --exit-code
